apiVersion: v2
description: "sentience"
name: sentience
version: 0.0.1
maintainers:
    - name: AlexanderLeschanz
      email: alexleschanz@icloud.com
      url: https://github.com/Creative-Difficulty
