imagePullSecrets: []
registry: ""
postgres:
  connectionString:
    valueFrom:
      secretKeyRef:
        name: postgres-cred
        key: connection_string

frontend:
  image: sylvanfranklin/sentience-frontend
  imagePullPolicy: Always
  replicas: 1
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"

backend:
  image: sylvanfranklin/sentience-backend
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"

