imagePullSecrets: []
registry: ""
postgres:
  connectionString:
    valueFrom:
      secretKeyRef:
        name: postgres-cred
        key: connectionString
discord: 
  token: 
    valueFrom:
      secretKeyRef:
        name: discord-cred 
        key: token
  guildId: 
    valueFrom:
      secretKeyRef:
        name: discord-cred 
        key: guildId
  scraperRoleId: 
    valueFrom:
      secretKeyRef:
        name: discord-cred 
        key: scraperRoleId
  introChannelId: 
    valueFrom:
      secretKeyRef:
        name: discord-cred 
        key: introChannelId

frontend:
  image: sylvanfranklin/sentience-frontend
  imagePullPolicy: Always
  replicas: 1
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"

backend:
  image: sylvanfranklin/sentience-backend
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"

