services:
    # For hosting the DB on the same machine
    db:
        image: pgvector/pgvector:pg16
        profiles: ["localdb"]

        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: sylvan
            POSTGRES_PASSWORD: sylvanpassword
            POSTGRES_DB: sylvan_db
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        depends_on:
            - frontend
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app/backend

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/app/frontend

volumes:
    pgdata:
