{{- $image := printf "%s%s" .Values.registry .Values.backend.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: backend
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.backend.resources }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
    {{- end }}
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/ready
        env: 
{{ include "sentience.postgres-env" . | indent 8 }}
